etcdservice:
  image: elcolio/etcd
  command: -advertise-client-urls http://docker_etcdservice_1:4001 
  ports:
    - "2379:2379"
    - "4001:4001"
  expose:
    - "2379"
    - "4001"

tomcatservice:
  build: ./tomcat
  ports:
    - "8081:8080"
  expose:
    - "8081"
  links:
    - etcdservice