etcdservice:
  image: elcolio/etcd
  command: -advertise-client-urls http://docker_etcdservice_1:4001 
  ports:
    - "2379:2379"
    - "4001:4001"
  expose:
    - "2379"
    - "4001"

httpdservice:
  build: ./httpd
  hostname: httpdservice
  ports:
    - "80:80"
    - "443:443"
  expose:
    - "80"
    - "443"
  links:
    - tomcatservice1
    - tomcatservice2

tomcatservice1:
  build: ./tomcat
  hostname: tomcatservice1
  ports:
    - "8081:8080"
  expose:
    - "8081"
  links:
    - etcdservice

tomcatservice2:
  build: ./tomcat
  hostname: tomcatservice2
  ports:
    - "8082:8080"
  expose:
    - "8082"
  links:
    - etcdservice

